server:
  port: 8084

spring:
  application:
    name: UnderWritingRiskService
  r2dbc:
    url: r2dbc:mysql://localhost:3306/underwriting_db
    username: root
    password: ""
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
