server:
  port: 8083

spring:
  application:
    name: PetService
  r2dbc:
    url: r2dbc:mysql://localhost:3306/pet_db
    username: root
    password: ""
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
